"""Vietnamese TTS drafts keyed by original speech filename.

Drafts were translated from machine-recognized English audio. Accuracy of the
underlying English transcripts requires listening review. These captions are
not approved final dialogue. Only speech recordings should be mapped here.
"""
from __future__ import annotations

# ASR draft translations. Voice clips without an English draft are not guessed.
ASR_DRAFT_VI = {
    "bastard_zombie_shield_a": "Zombie chống bạo động đã xuất hiện! Nó tiến đến như zombie bình thường, nhưng mỗi lần trúng đạn, nó sẽ giương một tấm khiên kim loại khổng lồ và trở nên bất khả xâm phạm trong vài giây. Hãy bắn những zombie khác trước. Khi nghe tiếng nó kéo lê khiên và tiến tới, nghĩa là bạn có thể bắn nó tiếp!",
    "bastard_maya_10_2": "Vừa rồi chỉ là khởi động thôi. Giờ mới đến thử thách thực sự!",
    "bastard_maya_10_3": "Chúc mừng! Ngươi đã vượt qua thử thách! Đùa đấy! Làm gì có chuyện dễ thế. Muốn thắng ư? Vậy thì sống sót qua màn này đi!",
    "bastard_maya_10_4": "Cái gì?! Ta cứ tưởng chẳng con người nào sống sót nổi đoạn vừa rồi! Ngươi làm thế nào? Không thể giỏi đến mức đó được! Thôi được, ta sẽ sớm kiểm chứng ở đấu trường tiếp theo. Ngươi sẽ phải đợi một chút. Ta còn phải thu xếp vài việc: đút lót vài người, thuê công nhân rẻ mạt, đào thêm mộ để lấy xác hồi sinh. Trong lúc đó, sao không thử chế độ Vô tận? Ở đó ngươi có thể kiếm xu, kim cương và nhất là tự chọn bộ vũ khí. Tạm biệt, chiến binh mù!",
    "bastard_ruins_intro": "Chào mừng đến đấu trường kỳ lạ nhất của ta! Nghe thác nước tuyệt đẹp kia không? Ta rất thích khu rừng này. Nó nhắc ta nhớ rằng tất cả chỉ là những con thú đang tìm cách ăn thịt lẫn nhau. Thưa quý khán giả, ta hân hạnh giới thiệu Chiến binh mù! Đừng mong họ reo hò, chiến binh mù ạ. Người ở đây đã cắt lưỡi trong các nghi lễ hiến tế. Còn vỗ tay thì không thể, vì ta đã cắt hết tay họ rồi. Nào, xem ngươi xoay xở thế nào tại Tàn tích Maya!",
    "bastard_maya_1_1": "Chà chà, ngươi phải làm quen với rừng rậm thật nhanh đấy. Cứ thế phát huy!",
    "bastard_passerby_storm_a": "Giông bão! Thật kịch tính! Thời điểm tuyệt vời để giết zombie. Chỉ có điều tiếng sấm đôi lúc sẽ làm ngươi điếc tai thôi!",
    "bastard_maya_2_2": "Được rồi. Ai đó mang cho chiến binh mù một chiếc ô! Chúng ta không muốn nhà vô địch bị cảm lạnh đâu.",
    "bastard_zombie_horde_c": "Ta không biết ngươi thấy sao, nhưng thế này dễ quá. Đã đến lúc thả một bầy zombie thật sự rồi!",
    "bastard_maya_3_1": "Vẫn chịu nổi chứ? Có đang tiết kiệm đạn không? Ta mong là có. Vì chúng ta mới đi được nửa đường thôi! Ha ha!",
    "bastard_maya_3_2": "Phù! Vừa rồi căng thẳng thật, đúng không?",
    "bastard_passerby_cows_a": "Thả bò ra! Đúng, đúng, chúng vô hại. Nhưng chúng là những con bò đáng sợ! Một nỗi kinh hoàng! Ta ghét bò!",
    "bastard_maya_4_2": "Có vẻ tối nay chúng ta được ăn bít tết rồi. Ha ha ha!",
    "bastard_zombie_whisperer_a": "Giờ hơi đáng sợ rồi đây. Ta vừa thả vài zombie Whisperer. Có thể ngươi chẳng nhận ra chúng đâu. Chúng rất im lặng cho đến khi tiến sát. Rồi chúng hét lên một tiếng lạnh sống lưng, và ngươi sẽ biết chúng đã đến. Nhưng lúc ấy có lẽ quá muộn để phản ứng. Để xem ngươi sống sót thế nào! Ha ha ha!",
    "bastard_maya_5_2": "Khó tìm con vừa rồi lắm à? Vậy hãy thử tìm con tiếp theo giữa đám zombie khác đi! Ha ha!",
    "bastard_maya_5_3": "Thật khó chịu khi ta giới thiệu zombie mới mà ngươi lại giết hết chúng! Để ta thử thêm lần nữa. Hãy tìm con Whisperer cuối cùng đi. Ta mong ngươi không tìm thấy nó!",
    "bastard_maya_5_4": "Được rồi, ngươi vượt qua thử thách này. Muốn gì nữa? Một tràng pháo tay à? Được thôi! Giờ cút đi, đến Kho vũ khí mua một khẩu súng trường chiến thuật. Ngươi sẽ cần nó ở thử thách tiếp theo!",
    "bastard_maya_6_1": "Tốt! Ngươi đã có súng trường chiến thuật. Cứ coi đó là người anh lớn của khẩu Micro SMG. Ngươi sẽ gắn bó với nó khá lâu đấy. Nào, cười lên, khán giả đang theo dõi! Để xem ngươi có thành thạo khẩu súng mới không!",
    "bastard_maya_6_2": "Tưởng đã nắm được cách chơi rồi sao? Chưa đâu! Một đợt zombie khác đang đến!",
    "bastard_maya_6_3": "Và bùm! Giờ ngươi là bậc thầy súng trường chiến thuật!",
    "bastard_maya_7_1": "Ngươi đang quá thoải mái đấy, chiến binh mù. Vì vậy, ta chỉ cho ngươi rất ít đạn ở thử thách này. Đừng bắn hụt viên nào. Dĩ nhiên ngươi vẫn có thể dùng vũ khí cận chiến, nhưng giết zombie từ xa luôn an toàn hơn. Bắt đầu nào!",
    "bastard_maya_7_2": "Ngươi nên cảm ơn ta vì đã ép ngươi ra khỏi vùng an toàn. Những việc như thế mới giúp con người tiến bộ!",
    "bastard_zombie_berserk_a": "Đã đến lúc cho ngươi gặp thứ mới. Đây là Berserk. Nó cũng mù như ngươi, nên thường chậm rãi đi quanh đánh hơi. Cứ để yên, nó sẽ tự bỏ đi. Hoặc ngươi cứ bắn cho nó nổi điên rồi đuổi theo ngươi. Loại này gần như không thể giết nổi, ta cảnh báo đấy! Giờ ta đã giới thiệu xong, để ta thả một con xuống đấu trường cho hai người làm quen!",
    "bastard_maya_8_2": "Ờ, màn đó dễ thôi. Nhưng sống sót trước Berserk sẽ khó hơn khi bị gây áp lực. Để ta làm ngươi căng thẳng thêm!",
    "bastard_maya_8_3": "Ta có cảm giác ngươi vẫn chưa đủ căng thẳng. Để ta sửa bằng một bầy zombie mới, kèm thêm Berserk!",
    "bastard_maya_8_4": "Ta rất muốn tiếp tục thả zombie vào ngươi, nhưng hết zombie mất rồi! Ta phải xuống phòng thí nghiệm hồi sinh thêm vài xác. À, ngươi cần tới Kho vũ khí mua cây đàn banjo cho thử thách sau. Đúng, ta nói banjo đấy! Mua đi!",
    "bastard_maya_9_1": "Ta trả lại khẩu súng lục cũ và Micro SMG cho ngươi, cùng một nhúm đạn ít ỏi. Đừng lo! Ngươi có cây đàn banjo không? Nó tốt hơn chảo rán và đập zombie còn buồn cười hơn. Đồng ý chứ? Mà thôi, ta chẳng quan tâm. Cứ giết lũ zombie đi!",
    "bastard_maya_9_2": "Ngươi vừa sáng tạo ra một thể loại âm nhạc mới bằng màn biểu diễn vừa rồi đấy. Ta thích lắm!",
    "bastard_tutorial_10_1": "Chào mừng đến bài kiểm tra cuối. Có vẻ ngươi có thói quen sống sót rất khó chịu, chiến binh mù ạ. Nhưng từ trước tới nay, ngươi chỉ đánh với những thí nghiệm zombie yếu nhất của ta. Chúng rên rỉ rồi chậm chạp đi thẳng về phía ngươi. Giờ ta muốn thêm chút gay cấn bằng zombie cưa máy, loại khán giả yêu thích nhất! Nó sẽ vừa tiến tới vừa chạy vòng quanh, nhanh hơn những người bạn yếu ớt một chút. Hãy lắng nghe thật kỹ và sống sót!",
    "bastard_tutorial_10_2": "Cái gì? Không, vừa rồi chỉ là may mắn! Thả thêm một con cưa máy nữa!",
    "bastard_tutorial_10_3": "Giờ thì thử với âm nhạc nào! Ngươi biết không, những zombie đáng sợ nhất của ta đều có nhạc nền riêng. Ta không muốn làm ngươi phân tâm, nhưng xem ngươi giỏi đến thế thì chắc chẳng phiền chút nhạc hùng tráng trong lúc chiến đấu đâu nhỉ!",
    "bastard_tutorial_10_4": "Ha ha! Ngươi sống sót qua bài kiểm tra cuối! Có lẽ ngươi thật sự là chiến binh huyền thoại. Vậy là ngươi được tuyển! Chúc mừng, chiến binh mù! Mở tiệc nào! Được rồi, hết tiệc. Ngươi vẫn chưa sẵn sàng bước vào đấu trường zombie lớn của ta. Ta phải rèn luyện ngươi thêm. Trước hết ta sẽ đưa ngươi tới những đấu trường nhỏ, cho danh tiếng của ngươi lan rộng khi vượt qua những thử thách thực sự. Khi đã thành cựu binh, ta sẽ cho ngươi vào đấu trường zombie riêng, nơi chỉ những chiến binh giỏi nhất được phép góp mặt!",
    "bastard_tutorial_1_1": "Hù! Ha ha! Ta làm ngươi sợ à? Chào mừng buổi tuyển chọn cho Đấu trường zombie của tiến sĩ Bastard! Ta là tiến sĩ Bastard, còn ngươi là Chiến binh mù. Thật sao? Vui đây! Nghe này, chiến binh mù, ta cần một anh hùng mới cho chương trình của mình. Một nhà vô địch dũng cảm để khán giả yêu mến và hoan hô. Ngươi có thể là người đó, nếu tài chiến đấu đúng như lời ngươi khoe. Còn nơi nào tốt hơn nhà hát La Mã đổ nát này để thử sức? Ta còn có giàn thiêu đằng kia để sưởi ấm cho ngươi. Hoặc thiêu xác ngươi nếu mọi chuyện không suôn sẻ. Nào, làm vài bài kiểm tra xem ngươi có bản lĩnh không! Xoay người, khởi động cổ, vặn mình nào!",
    "bastard_tutorial_1_2": "Được rồi, đủ rồi. Dừng lại! Giờ xem ngươi có đủ gan chĩa súng vào zombie và bắn hạ nó trước khi bị ăn sống không. Vì đó chính là chuyện sẽ xảy ra nếu zombie của ta đến sát ngươi. Ta sẽ thả Bob, một con zombie. Đừng lo, nó không tấn công được đâu, vì đã bị xích vào tường. Cứ thong thả ngắm, rồi bắn nó!",
    "bastard_tutorial_1_4": "Tuyệt vời! Chắc thế. Ta có nhìn đâu. Không sao. Giờ ta sẽ thả một zombie khác. Ối, gạt nhầm cần rồi. Thử cái này. Hay cái kia? Không phải! Thôi thế này đi, ngươi nạp đạn trong lúc ta tìm đúng cần gạt trên bảng điều khiển ngu ngốc này!",
    "bastard_tutorial_1_5": "Rồi, tìm được cần đúng rồi. Ta sẽ thả Jim, anh em của Bob. Hãy chào Jim bằng cách bắn một viên vào sọ nó. Như lúc nãy: ngắm rồi bắn, ngắm rồi bắn!",
    "bastard_tutorial_1_6": "Phù! Cảm giác thật tuyệt. Ồ! Ta quên mất ngươi và Jim. Ngươi giết nó rồi à? Tiếc thật, ta rất muốn xem. Dù sao ngươi đã vượt bài kiểm tra đầu tiên. Chúc mừng! Ta sẽ không vỗ lưng khen ngươi đâu, vì ta thấy an toàn hơn nhiều trong phòng điều khiển chống đạn này. Hẹn gặp ở thử thách tiếp theo!",
    "bastard_tutorial_2_1": "Ồ, có vẻ ngươi hết đạn rồi. Không sao. Ta cho các chiến binh mang theo hai khẩu súng cùng lúc. Thật ra ta thấy ngươi có khẩu lớn hơn ở thắt lưng. Nào, đổi vũ khí đi!",
    "bastard_tutorial_2_2": "Ngươi không có đạn vô hạn trong thử thách của ta, nên đừng nghĩ đến chuyện nhắm mắt xả súng. Giờ bắn con zombie khác cho ta xem nào. Lần này ta hứa sẽ chăm chú quan sát ngươi, chiến binh mù! Sẵn sàng hay chưa, Ted xác sống đến đây! Ối, xin lỗi, lại nhầm cần gạt.",
    "bastard_tutorial_2_3": "Ấn tượng thật. Vô cùng ấn... Ối, ta lại bỏ lỡ rồi, đúng không? Mải nhìn kết quả kiểm tra chỉ số thông minh của chính mình. Thế này nhé, ta sẽ thả hai zombie thay vì một để khỏi buồn chán. Ta đã hồi sinh Bob và Jim, phòng lúc có chuyện như thế này!",
    "bastard_tutorial_2_4": "Ha ha! Lần này ta nhìn thấy rồi! Ta thấy ngươi bắn hạ cả hai con zombie! Thấy chưa, ai bảo ta không biết tập trung!",
    "bastard_tutorial_3_1": "Hãy tưởng tượng ngươi hết đạn giữa thử thách. Hoặc tệ hơn, còn đạn nhưng đang nạp nên không bắn được. Hoặc tệ hơn nữa, ta ăn cắp hết đạn của ngươi mà ngươi không hay, như ta vừa làm đây! Bởi vậy, chiến binh diệt zombie nào cũng mang vũ khí cận chiến, thứ có thể vung lên ngay lập tức. Ta đã chuẩn bị một món cho ngươi: chiếc chảo thép carbon. Thử đi! Vung nó lên nào!",
    "bastard_tutorial_3_2": "Ngươi có thích tiếng chảo kêu khi đập vào sọ zombie không? Nhưng làm sao biết zombie đã đủ gần để vung trúng? Câu hỏi hay đấy, chiến binh mù. Đáp án nằm ở trái tim ngươi. Thử ngay nhé! Ta sẽ thả Bob, ngươi đã gặp nó rồi. Hãy cho ta thấy mặt tàn bạo nhất của ngươi bằng cách đập nó với chiếc chảo!",
    "bastard_tutorial_3_3": "Buồn cười quá, chiến binh mù! Ta bắt đầu ghét ngươi rồi đấy. Ngươi nghe thấy tim mình đập không? Giờ ta sẽ thả Jim thật gần, đủ để ngươi ngửi thấy hơi thở zombie thơm mát của nó, mùi hương ta thích nhất! Ngươi sẽ thấy tim đập nhanh hơn nhiều khi zombie ở ngay bên cạnh. Vì vậy hãy giết nó thật nhanh. Ta không muốn ngươi lên cơn đau tim đâu!",
    "bastard_tutorial_3_4": "Ha ha ha! Ngươi khiến hôm nay của ta thật tuyệt! Ha ha! Ta ghét ngươi quá đi mất!",
    "bastard_gameover_a": "Chết rồi à? Ồ, chết thật rồi sao? Chán thế!",
    "bastard_gameover_b": "Giỏi lắm! Hoan hô! Cái gì? Ngươi thất bại rồi à? Ha ha! Ối!",
    "bastard_gameover_c": "Ồ, ta vừa bắt đầu thích ngươi thì ngươi đã thua mất rồi!",
    "bastard_gameover_d": "Ôi trời! Ai đó dọn cái đống lộn xộn này đi!",
    "bastard_gameover_e": "Ta thất vọng về ngươi quá!",
    "bastard_gameover_f": "Thật phí một mạng người. Nhưng không sao, ta vẫn có thể tận dụng xác ngươi.",
    "bastard_gameover_g": "Nhìn ngươi kìa! Nhìn ngươi chết ngay dưới chân ta kìa! Ha ha ha!",
    "bastard_gameover_h": "Suỵt! Không sao đâu.",
    "bastard_gameover_i": "Không! Không! Không! Ta đâu trả tiền để ngươi bị ăn sống sớm thế này!",
    "bastard_gameover_j": "Thế là xong! Bùm!",
    "bastard_gameover_k": "Ha ha ha! Ngươi thua rồi! Ha ha ha!",
    "bastard_gameover_l": "Cũng không tệ đến thế đâu! Ít nhất ngươi... Ồ, ta lừa ai chứ? Tệ khủng khiếp!",
    "bastard_gameover_m": "Chết tiệt! Cảnh vừa rồi thật kinh khủng! Ta thích lắm!",
    "bastard_gameover_n": "Ối! Chuyện đó lẽ ra chưa được xảy ra!",
    "bastard_gameover_o": "Mang bộ dụng cụ hồi sinh zombie đến đây! Xác này vẫn còn mới!",
    "OPENER_DRBASTARD_B_SPA": "Và bắt đầu nào!",
    "OPENER_DRBASTARD_SPA": "Và bắt đầu nào!",
    "OPENER_LIFT_VOICE_1_SPA": "Đang đi lên.",
    "OPENER_LIFT_VOICE_2_SPA": "Tầng ba. Đấu trường chính.",
    "revive_no": "Hết rồi!",
    "revive_yes": "Audio Defence!",
    "announcer_revive_a": "Hồi sinh!",
    "announcer_revive_b": "Hồi sinh!",
    "announcer_reviveyes": "Đứng dậy nào!",
    "announcer_tutorial_aimhelp": "Nếu khó tìm thấy zombie, hãy thử xoay người. Biết đâu nó đang ở phía sau bạn.",
    "announcer_tutorial_aimprompt": "Hãy thử xoay người và cảm nhận thế giới âm thanh thay đổi theo chuyển động của bạn.",
}


def draft_for(sound_key: str | None) -> str | None:
    return ASR_DRAFT_VI.get(sound_key or "")
