"""Vietnamese TTS drafts keyed by original speech filename.

Drafts were translated from machine-recognized English audio. Accuracy of the
underlying English transcripts requires listening review. These captions are
not approved final dialogue. Only speech recordings should be mapped here.
"""
from __future__ import annotations

# ASR draft translations. Voice clips without an English draft are not guessed.
ASR_DRAFT_VI = {
    "bastard_zombie_shield_a": "Zombie chống bạo động đã xuất hiện! Nó tiến đến như zombie bình thường, nhưng mỗi lần trúng đạn, nó sẽ giương một tấm khiên kim loại khổng lồ và trở nên bất khả xâm phạm trong vài giây. Hãy bắn những zombie khác trước. Khi nghe tiếng nó kéo lê khiên và tiến tới, nghĩa là bạn có thể bắn nó tiếp!",
    "bastard_maya_10_2": "Vừa rồi chỉ là khởi động thôi. Giờ mới đến thử thách thực sự!",
    "bastard_maya_10_3": "Chúc mừng! Ngươi đã vượt qua thử thách! Đùa đấy! Làm gì có chuyện dễ thế. Muốn thắng ư? Vậy thì sống sót qua màn này đi!",
    "bastard_maya_10_4": "Cái gì?! Ta cứ tưởng chẳng con người nào sống sót nổi đoạn vừa rồi! Ngươi làm thế nào? Không thể giỏi đến mức đó được! Thôi được, ta sẽ sớm kiểm chứng ở đấu trường tiếp theo. Ngươi sẽ phải đợi một chút. Ta còn phải thu xếp vài việc: đút lót vài người, thuê công nhân rẻ mạt, đào thêm mộ để lấy xác hồi sinh. Trong lúc đó, sao không thử chế độ Vô tận? Ở đó ngươi có thể kiếm xu, kim cương và nhất là tự chọn bộ vũ khí. Tạm biệt, chiến binh mù!",
    "bastard_ruins_intro": "Chào mừng đến đấu trường kỳ lạ nhất của ta! Nghe thác nước tuyệt đẹp kia không? Ta rất thích khu rừng này. Nó nhắc ta nhớ rằng tất cả chỉ là những con thú đang tìm cách ăn thịt lẫn nhau. Thưa quý khán giả, ta hân hạnh giới thiệu Chiến binh mù! Đừng mong họ reo hò, chiến binh mù ạ. Người ở đây đã cắt lưỡi trong các nghi lễ hiến tế. Còn vỗ tay thì không thể, vì ta đã cắt hết tay họ rồi. Nào, xem ngươi xoay xở thế nào tại Tàn tích Maya!",
    "bastard_maya_1_1": "Chà chà, ngươi phải làm quen với rừng rậm thật nhanh đấy. Cứ thế phát huy!",
    "bastard_passerby_storm_a": "Giông bão! Thật kịch tính! Thời điểm tuyệt vời để giết zombie. Chỉ có điều tiếng sấm đôi lúc sẽ làm ngươi điếc tai thôi!",
    "bastard_maya_2_2": "Được rồi. Ai đó mang cho chiến binh mù một chiếc ô! Chúng ta không muốn nhà vô địch bị cảm lạnh đâu.",
    "bastard_zombie_horde_c": "Ta không biết ngươi thấy sao, nhưng thế này dễ quá. Đã đến lúc thả một bầy zombie thật sự rồi!",
    "bastard_maya_3_1": "Vẫn chịu nổi chứ? Có đang tiết kiệm đạn không? Ta mong là có. Vì chúng ta mới đi được nửa đường thôi! Ha ha!",
    "bastard_maya_3_2": "Phù! Vừa rồi căng thẳng thật, đúng không?",
    "bastard_passerby_cows_a": "Thả bò ra! Đúng, đúng, chúng vô hại. Nhưng chúng là những con bò đáng sợ! Một nỗi kinh hoàng! Ta ghét bò!",
    "bastard_maya_4_2": "Có vẻ tối nay chúng ta được ăn bít tết rồi. Ha ha ha!",
    "bastard_zombie_whisperer_a": "Giờ hơi đáng sợ rồi đây. Ta vừa thả vài zombie Whisperer. Có thể ngươi chẳng nhận ra chúng đâu. Chúng rất im lặng cho đến khi tiến sát. Rồi chúng hét lên một tiếng lạnh sống lưng, và ngươi sẽ biết chúng đã đến. Nhưng lúc ấy có lẽ quá muộn để phản ứng. Để xem ngươi sống sót thế nào! Ha ha ha!",
    "bastard_maya_5_2": "Khó tìm con vừa rồi lắm à? Vậy hãy thử tìm con tiếp theo giữa đám zombie khác đi! Ha ha!",
    "bastard_maya_5_3": "Thật khó chịu khi ta giới thiệu zombie mới mà ngươi lại giết hết chúng! Để ta thử thêm lần nữa. Hãy tìm con Whisperer cuối cùng đi. Ta mong ngươi không tìm thấy nó!",
    "bastard_maya_5_4": "Được rồi, ngươi vượt qua thử thách này. Muốn gì nữa? Một tràng pháo tay à? Được thôi! Giờ cút đi, đến Kho vũ khí mua một khẩu súng trường chiến thuật. Ngươi sẽ cần nó ở thử thách tiếp theo!",
    "bastard_maya_6_1": "Tốt! Ngươi đã có súng trường chiến thuật. Cứ coi đó là người anh lớn của khẩu Micro SMG. Ngươi sẽ gắn bó với nó khá lâu đấy. Nào, cười lên, khán giả đang theo dõi! Để xem ngươi có thành thạo khẩu súng mới không!",
    "bastard_maya_6_2": "Tưởng đã nắm được cách chơi rồi sao? Chưa đâu! Một đợt zombie khác đang đến!",
    "bastard_maya_6_3": "Và bùm! Giờ ngươi là bậc thầy súng trường chiến thuật!",
    "bastard_maya_7_1": "Ngươi đang quá thoải mái đấy, chiến binh mù. Vì vậy, ta chỉ cho ngươi rất ít đạn ở thử thách này. Đừng bắn hụt viên nào. Dĩ nhiên ngươi vẫn có thể dùng vũ khí cận chiến, nhưng giết zombie từ xa luôn an toàn hơn. Bắt đầu nào!",
    "bastard_maya_7_2": "Ngươi nên cảm ơn ta vì đã ép ngươi ra khỏi vùng an toàn. Những việc như thế mới giúp con người tiến bộ!",
    "bastard_zombie_berserk_a": "Đã đến lúc cho ngươi gặp thứ mới. Đây là Berserk. Nó cũng mù như ngươi, nên thường chậm rãi đi quanh đánh hơi. Cứ để yên, nó sẽ tự bỏ đi. Hoặc ngươi cứ bắn cho nó nổi điên rồi đuổi theo ngươi. Loại này gần như không thể giết nổi, ta cảnh báo đấy! Giờ ta đã giới thiệu xong, để ta thả một con xuống đấu trường cho hai người làm quen!",
    "bastard_maya_8_2": "Ờ, màn đó dễ thôi. Nhưng sống sót trước Berserk sẽ khó hơn khi bị gây áp lực. Để ta làm ngươi căng thẳng thêm!",
    "bastard_maya_8_3": "Ta có cảm giác ngươi vẫn chưa đủ căng thẳng. Để ta sửa bằng một bầy zombie mới, kèm thêm Berserk!",
    "bastard_maya_8_4": "Ta rất muốn tiếp tục thả zombie vào ngươi, nhưng hết zombie mất rồi! Ta phải xuống phòng thí nghiệm hồi sinh thêm vài xác. À, ngươi cần tới Kho vũ khí mua cây đàn banjo cho thử thách sau. Đúng, ta nói banjo đấy! Mua đi!",
    "bastard_maya_9_1": "Ta trả lại khẩu súng lục cũ và Micro SMG cho ngươi, cùng một nhúm đạn ít ỏi. Đừng lo! Ngươi có cây đàn banjo không? Nó tốt hơn chảo rán và đập zombie còn buồn cười hơn. Đồng ý chứ? Mà thôi, ta chẳng quan tâm. Cứ giết lũ zombie đi!",
    "bastard_maya_9_2": "Ngươi vừa sáng tạo ra một thể loại âm nhạc mới bằng màn biểu diễn vừa rồi đấy. Ta thích lắm!",
    "bastard_tutorial_10_1": "Chào mừng đến bài kiểm tra cuối. Có vẻ ngươi có thói quen sống sót rất khó chịu, chiến binh mù ạ. Nhưng từ trước tới nay, ngươi chỉ đánh với những thí nghiệm zombie yếu nhất của ta. Chúng rên rỉ rồi chậm chạp đi thẳng về phía ngươi. Giờ ta muốn thêm chút gay cấn bằng zombie cưa máy, loại khán giả yêu thích nhất! Nó sẽ vừa tiến tới vừa chạy vòng quanh, nhanh hơn những người bạn yếu ớt một chút. Hãy lắng nghe thật kỹ và sống sót!",
    "bastard_tutorial_10_2": "Cái gì? Không, vừa rồi chỉ là may mắn! Thả thêm một con cưa máy nữa!",
    "bastard_tutorial_10_3": "Giờ thì thử với âm nhạc nào! Ngươi biết không, những zombie đáng sợ nhất của ta đều có nhạc nền riêng. Ta không muốn làm ngươi phân tâm, nhưng xem ngươi giỏi đến thế thì chắc chẳng phiền chút nhạc hùng tráng trong lúc chiến đấu đâu nhỉ!",
    "bastard_tutorial_10_4": "Ha ha! Ngươi sống sót qua bài kiểm tra cuối! Có lẽ ngươi thật sự là chiến binh huyền thoại. Vậy là ngươi được tuyển! Chúc mừng, chiến binh mù! Mở tiệc nào! Được rồi, hết tiệc. Ngươi vẫn chưa sẵn sàng bước vào đấu trường zombie lớn của ta. Ta phải rèn luyện ngươi thêm. Trước hết ta sẽ đưa ngươi tới những đấu trường nhỏ, cho danh tiếng của ngươi lan rộng khi vượt qua những thử thách thực sự. Khi đã thành cựu binh, ta sẽ cho ngươi vào đấu trường zombie riêng, nơi chỉ những chiến binh giỏi nhất được phép góp mặt!",
    "bastard_tutorial_1_1": "Hù! Ha ha! Ta làm ngươi sợ à? Chào mừng buổi tuyển chọn cho Đấu trường zombie của tiến sĩ Bastard! Ta là tiến sĩ Bastard, còn ngươi là Chiến binh mù. Thật sao? Vui đây! Nghe này, chiến binh mù, ta cần một anh hùng mới cho chương trình của mình. Một nhà vô địch dũng cảm để khán giả yêu mến và hoan hô. Ngươi có thể là người đó, nếu tài chiến đấu đúng như lời ngươi khoe. Còn nơi nào tốt hơn nhà hát La Mã đổ nát này để thử sức? Ta còn có giàn thiêu đằng kia để sưởi ấm cho ngươi. Hoặc thiêu xác ngươi nếu mọi chuyện không suôn sẻ. Nào, làm vài bài kiểm tra xem ngươi có bản lĩnh không! Xoay người, khởi động cổ, vặn mình nào!",
    "bastard_tutorial_1_2": "Được rồi, đủ rồi. Dừng lại! Giờ xem ngươi có đủ gan chĩa súng vào zombie và bắn hạ nó trước khi bị ăn sống không. Vì đó chính là chuyện sẽ xảy ra nếu zombie của ta đến sát ngươi. Ta sẽ thả Bob, một con zombie. Đừng lo, nó không tấn công được đâu, vì đã bị xích vào tường. Cứ thong thả ngắm, rồi bắn nó!",
    "bastard_tutorial_1_4": "Tuyệt vời! Chắc thế. Ta có nhìn đâu. Không sao. Giờ ta sẽ thả một zombie khác. Ối, gạt nhầm cần rồi. Thử cái này. Hay cái kia? Không phải! Thôi thế này đi, ngươi nạp đạn trong lúc ta tìm đúng cần gạt trên bảng điều khiển ngu ngốc này!",
    "bastard_tutorial_1_5": "Rồi, tìm được cần đúng rồi. Ta sẽ thả Jim, anh em của Bob. Hãy chào Jim bằng cách bắn một viên vào sọ nó. Như lúc nãy: ngắm rồi bắn, ngắm rồi bắn!",
    "bastard_tutorial_1_6": "Phù! Cảm giác thật tuyệt. Ồ! Ta quên mất ngươi và Jim. Ngươi giết nó rồi à? Tiếc thật, ta rất muốn xem. Dù sao ngươi đã vượt bài kiểm tra đầu tiên. Chúc mừng! Ta sẽ không vỗ lưng khen ngươi đâu, vì ta thấy an toàn hơn nhiều trong phòng điều khiển chống đạn này. Hẹn gặp ở thử thách tiếp theo!",
    "bastard_tutorial_2_1": "Ồ, có vẻ ngươi hết đạn rồi. Không sao. Ta cho các chiến binh mang theo hai khẩu súng cùng lúc. Thật ra ta thấy ngươi có khẩu lớn hơn ở thắt lưng. Nào, đổi vũ khí đi!",
    "bastard_tutorial_2_2": "Ngươi không có đạn vô hạn trong thử thách của ta, nên đừng nghĩ đến chuyện nhắm mắt xả súng. Giờ bắn con zombie khác cho ta xem nào. Lần này ta hứa sẽ chăm chú quan sát ngươi, chiến binh mù! Sẵn sàng hay chưa, Ted xác sống đến đây! Ối, xin lỗi, lại nhầm cần gạt.",
    "bastard_tutorial_2_3": "Ấn tượng thật. Vô cùng ấn... Ối, ta lại bỏ lỡ rồi, đúng không? Mải nhìn kết quả kiểm tra chỉ số thông minh của chính mình. Thế này nhé, ta sẽ thả hai zombie thay vì một để khỏi buồn chán. Ta đã hồi sinh Bob và Jim, phòng lúc có chuyện như thế này!",
    "bastard_tutorial_2_4": "Ha ha! Lần này ta nhìn thấy rồi! Ta thấy ngươi bắn hạ cả hai con zombie! Thấy chưa, ai bảo ta không biết tập trung!",
    "bastard_tutorial_3_1": "Hãy tưởng tượng ngươi hết đạn giữa thử thách. Hoặc tệ hơn, còn đạn nhưng đang nạp nên không bắn được. Hoặc tệ hơn nữa, ta ăn cắp hết đạn của ngươi mà ngươi không hay, như ta vừa làm đây! Bởi vậy, chiến binh diệt zombie nào cũng mang vũ khí cận chiến, thứ có thể vung lên ngay lập tức. Ta đã chuẩn bị một món cho ngươi: chiếc chảo thép carbon. Thử đi! Vung nó lên nào!",
    "bastard_tutorial_3_2": "Ngươi có thích tiếng chảo kêu khi đập vào sọ zombie không? Nhưng làm sao biết zombie đã đủ gần để vung trúng? Câu hỏi hay đấy, chiến binh mù. Đáp án nằm ở trái tim ngươi. Thử ngay nhé! Ta sẽ thả Bob, ngươi đã gặp nó rồi. Hãy cho ta thấy mặt tàn bạo nhất của ngươi bằng cách đập nó với chiếc chảo!",
    "bastard_tutorial_3_3": "Buồn cười quá, chiến binh mù! Ta bắt đầu ghét ngươi rồi đấy. Ngươi nghe thấy tim mình đập không? Giờ ta sẽ thả Jim thật gần, đủ để ngươi ngửi thấy hơi thở zombie thơm mát của nó, mùi hương ta thích nhất! Ngươi sẽ thấy tim đập nhanh hơn nhiều khi zombie ở ngay bên cạnh. Vì vậy hãy giết nó thật nhanh. Ta không muốn ngươi lên cơn đau tim đâu!",
    "bastard_tutorial_3_4": "Ha ha ha! Ngươi khiến hôm nay của ta thật tuyệt! Ha ha! Ta ghét ngươi quá đi mất!",
    "bastard_gameover_a": "Chết rồi à? Ồ, chết thật rồi sao? Chán thế!",
    "bastard_gameover_b": "Giỏi lắm! Hoan hô! Cái gì? Ngươi thất bại rồi à? Ha ha! Ối!",
    "bastard_gameover_c": "Ồ, ta vừa bắt đầu thích ngươi thì ngươi đã thua mất rồi!",
    "bastard_gameover_d": "Ôi trời! Ai đó dọn cái đống lộn xộn này đi!",
    "bastard_gameover_e": "Ta thất vọng về ngươi quá!",
    "bastard_gameover_f": "Thật phí một mạng người. Nhưng không sao, ta vẫn có thể tận dụng xác ngươi.",
    "bastard_gameover_g": "Nhìn ngươi kìa! Nhìn ngươi chết ngay dưới chân ta kìa! Ha ha ha!",
    "bastard_gameover_h": "Suỵt! Không sao đâu.",
    "bastard_gameover_i": "Không! Không! Không! Ta đâu trả tiền để ngươi bị ăn sống sớm thế này!",
    "bastard_gameover_j": "Thế là xong! Bùm!",
    "bastard_gameover_k": "Ha ha ha! Ngươi thua rồi! Ha ha ha!",
    "bastard_gameover_l": "Cũng không tệ đến thế đâu! Ít nhất ngươi... Ồ, ta lừa ai chứ? Tệ khủng khiếp!",
    "bastard_gameover_m": "Chết tiệt! Cảnh vừa rồi thật kinh khủng! Ta thích lắm!",
    "bastard_gameover_n": "Ối! Chuyện đó lẽ ra chưa được xảy ra!",
    "bastard_gameover_o": "Mang bộ dụng cụ hồi sinh zombie đến đây! Xác này vẫn còn mới!",
    "OPENER_DRBASTARD_B_SPA": "Và bắt đầu nào!",
    "OPENER_DRBASTARD_SPA": "Và bắt đầu nào!",
    "OPENER_LIFT_VOICE_1_SPA": "Đang đi lên.",
    "OPENER_LIFT_VOICE_2_SPA": "Tầng ba. Đấu trường chính.",
    "revive_no": "Hết rồi!",
    "revive_yes": "Audio Defence!",
    "announcer_revive_a": "Hồi sinh!",
    "announcer_revive_b": "Hồi sinh!",
    "announcer_reviveyes": "Đứng dậy nào!",
    "announcer_tutorial_aimhelp": "Nếu khó tìm thấy zombie, hãy thử xoay người. Biết đâu nó đang ở phía sau bạn.",
    "announcer_tutorial_aimprompt": "Hãy thử xoay người và cảm nhận thế giới âm thanh thay đổi theo chuyển động của bạn.",
}


# Later Challenge recordings, from the complete English ASR pass.
# These also remain audio-unverified drafts until reviewed by listening.
ASR_DRAFT_VI.update({
    "bastard_tutorial_4_1": "Ai mà chẳng có lúc cần giúp đỡ, đúng không? Vì thế mới có vật phẩm hỗ trợ. Thỉnh thoảng ta gọi trực thăng thả xuống một chiếc máy quay thưởng rất nặng. Nó sẽ luôn cho phần thưởng nếu ngươi cho nó ăn đạn thay vì xu. Nhưng phải bắn nhanh, nếu không máy sẽ tắt và chẳng cho gì cả. Thử nào! Ta sẽ thả Bob, Jim và Ted cùng lúc. Trực thăng đang đến đấy, nhớ bắn máy quay thưởng khi nó rơi xuống!",
    "bastard_tutorial_4_2": "Ngươi có thích mùi thịt cháy còn vương trong không khí không? Ta nghĩ Pháo hoa là vật phẩm hỗ trợ yêu thích nhất của mình, nhưng ta còn nhiều loại khác lắm. Chẳng ai biết trước sẽ nhận được gì từ máy quay thưởng của ta. Làm thêm lần nữa xem ngươi được món nào!",
    "bastard_tutorial_4_4": "Xong rồi à? Ta vừa ra ngoài làm cho mình một chiếc bánh kẹp. Dù sao thì nhớ bài học nhé! Bắn máy quay thưởng ngay là tốt. Chờ quá lâu mới bắn là dở!",
    "bastard_tutorial_5_1": "Giờ nói về tiền nào. Ta trả công cho ngươi nếu sống sót qua thử thách. Ngắm bắn thật chính xác thì được thưởng thêm, bóp cò càng nhanh lại càng kiếm nhiều tiền. Ví dụ, nếu ta thả hai zombie không bị xích vào ngươi, ngươi sẽ làm gì? Ta biết chúng sẽ làm gì rồi: chúng sẽ ăn sống ngươi nếu đến đủ gần!",
    "bastard_tutorial_5_2": "Dễ mà, đúng không? Sống sót, ngắm chuẩn, bắn nhanh. Đó là cách kiếm tiền trong thử thách của ta. Nhưng tiền không phải tất cả. Chúng ta còn có kim cương! Một số vật phẩm trong Kho vũ khí bán bằng kim cương thay vì xu. Kim cương hiếm hơn xu rất nhiều. Muốn kiếm một ít không? Hãy bắn sinh vật nhỏ mà ta sắp thả đằng kia!",
    "bastard_tutorial_5_3": "Ta đa! Ngươi vừa nhặt viên kim cương đầu tiên! Những con ký sinh nhỏ này thích đồ lấp lánh hơn thịt người. Chúng không tấn công, nhưng nếu ngươi không bắn nhanh thì chúng sẽ chạy mất. Khó hơn ngươi tưởng đấy! Thử một tình huống thực tế và chết người nào. Hãy bắn zombie rồi lấy viên kim cương. Hoặc chết khi đang cố!",
    "bastard_tutorial_5_4": "Còn một điều cuối về kim cương. Ta chỉ thả chúng trong chế độ Vô tận, nơi ngươi sẽ được vào ngay sau thử thách này. Giờ ngươi đã hiểu cách làm giàu, ta hỏi nhé: Ngươi định làm gì với đống xu và kim cương ấy? Tất nhiên là mua thêm vũ khí! Hoặc nâng cấp những món đang có. Thế nên khi vượt xong thử thách, hãy đến Kho vũ khí chính thức của chúng ta và mua một khẩu súng mới. Ngươi cần súng shotgun nòng ngắn cho các thử thách tiếp theo. Mua xong thì quay lại, không thì đừng trở lại nữa!",
    "bastard_tutorial_6_1": "Ta rất thích shotgun! Sát thương khổng lồ ở cự ly gần, đạn tỏa rất rộng. Nếu ngắm tốt, một phát có thể bắn trúng nhiều zombie. Đặc biệt hữu dụng khi bị bao vây, như tình huống ngươi sắp gặp đây! Chúc may mắn sống sót! Ha ha ha!",
    "bastard_tutorial_6_2": "Chết tiệt, vừa rồi xem đã mắt thật! Hay đến mức ta có thể xem cả ngày. Vậy thì thêm zombie nhé. Giết chúng cho ta xem. Bỏng ngô ta đã chuẩn bị sẵn rồi!",
    "bastard_tutorial_6_3": "Ngươi làm được rồi! Sao không ăn mừng bằng một điệu nhảy chiến thắng nhỉ? Nào, nhảy cho ta xem. Ta nói nghiêm túc đấy. Nhảy đi! Xoay vòng nào, không ta giết ngươi bây giờ! Chẳng đẹp chút nào. Thôi được, quên chuyện nhảy múa đi, cứ tập trung bắn súng!",
    "bastard_tutorial_7_1": "Đến giờ ngươi chỉ đánh những zombie cổ điển của ta. Giờ ta sẽ giới thiệu một thí nghiệm mới. Ta bơm vào xác sống một lượng khí dễ nổ khủng khiếp. Khổ nỗi ta không tìm được cách ngăn khí rò rỉ, nên đặt tên nó là Farty! Đừng để nó áp sát, mà không chỉ vì mùi đâu. Để ta cho ngươi thấy tại sao. Thử giết con Farty này!",
    "bastard_tutorial_7_2": "Ngươi biết tiếng ù tai chính là dấu hiệu các tế bào tai đang chết dần không? Ta mong ngươi đã hiểu nên giết Farty trước khi nó đến gần như thế. Làm lại nào. Lần này ta sẽ thả một con Farty khác từ xa hơn!",
    "bastard_tutorial_7_3": "Khá hơn chứ? Giờ đến phần vui nhất! Zombie phát nổ cũng có điểm hay. Nếu một con Farty nổ ngay cạnh những zombie khác, cả đám sẽ bị thổi tung thành từng mảnh! Ha ha ha! Thử nào!",
    "bastard_tutorial_7_4": "Ồ, ngươi thắng rồi à? Ta có nhìn đâu!",
    "bastard_tutorial_8_1": "Đã đến lúc nghĩ đến nâng cấp vũ khí. Nếu ngươi muốn sống, đây là khoản đầu tư rất đáng giá. Nào, làm thí nghiệm nhỏ nhé. Ta sẽ thả nhiều zombie đến mức ngươi có lẽ sẽ chết. Đừng lo, ta là bác sĩ mà. Ta hồi sinh ngươi được. Ý ta là, nếu chết, hãy trở lại Kho vũ khí nâng cấp súng rồi mới chơi thử lần nữa. Chúc may mắn!",
    "bastard_tutorial_8_2": "Cái gì? Ngươi vẫn sống ư?! Chết tiệt, ta cứ nghĩ ngươi sẽ chết. Giờ chẳng biết tiếp tục thế nào. Thôi, ứng biến vậy!",
    "bastard_tutorial_9_1": "Ê! Ai để cái máy phát điện giữa đấu trường thế này? À đúng, chính ta! Sao, mất phương hướng hả, chiến binh mù? Cứ bắn nó vài phát, nó sẽ tắt được một lúc!",
    "bastard_tutorial_9_2": "Ngươi phải tập quen với những trò tăng độ khó nho nhỏ này, chiến binh mù ạ. Tất cả nhằm làm thử thách thú vị hơn. Cho khán giả xem!",
    "bastard_urban_10_1": "Hu hu! Tưởng giết được một con Hulk là ngươi vô địch thiên hạ rồi sao? Đó chỉ là màn nhử thôi. Thử thách thực sự bắt đầu ngay bây giờ!",
    "bastard_zombie_hulk_a": "Tối nay, ta hân hạnh giới thiệu Hulk! Đây là kết quả của việc tiêm cho zombie quá liều adrenaline, testosterone và cả hạt quinoa. Ta khuyên ngươi tập trung bắn nó ngay khi nghe tiếng gầm. Thứ này chịu đòn cực kỳ giỏi!",
    "bastard_urban_10_2": "Chưa đâu, ngươi mới đi được nửa đường thôi! Giờ đến tiết mục của Hulk với nhạc nền riêng, giai điệu quái vật!",
    "bastard_city_end": "Hoan hô! Quả là kỳ tích! Ta chưa từng thấy ai quyết tâm không chết như ngươi. Đến lúc thử bản năng sinh tồn của ngươi ở một nơi phù hợp hơn. Chúc mừng, chiến binh mù! Ngươi đã nhận vé vào đấu trường Tàn tích Maya của ta. Nhớ tiêm phòng sốt rét đấy!",
    "bastard_city_intro": "Chào mừng đến một số mới của Đấu trường zombie, do tiến sĩ Bastard tổ chức! Chương trình tối nay diễn ra ở ngã tư rộng lớn của thành phố, rực sáng nhờ đống xe đang cháy. Kính thưa quý khán giả, xin giới thiệu Chiến binh mù! À khoan, làm gì có khán giả nào ở đây! Ha ha ha! Đây là thành phố bị bỏ hoang mà. Ngươi phải tự giành lấy quyền được mọi người reo hò, chiến binh mù ạ. Giờ hãy sống sót qua bữa tiệc chào mừng chết người của ta!",
    "bastard_urban_1_1": "Nghe tiếng còi báo hiệu đó không? Ngươi nên tập yêu thích âm thanh ấy. Nó có nghĩa là ngươi đã vượt qua thử thách! Ngày không còn nghe tiếng còi nữa sẽ là ngày ngươi chết trong đấu trường. Rồi ngày đó cũng đến thôi... nhưng không phải hôm nay!",
    "bastard_passerby_cars_a": "Biết điều gì giúp chương trình ăn khách hơn không? Những vụ nổ! Vì thế ta đã đậu rất nhiều xe quanh ngươi. Chuông báo động của chúng sẽ thỉnh thoảng lại kêu. Nếu không muốn nghe bản giao hưởng còi xe giữa lúc đánh zombie, tốt nhất hãy bắn cho mấy chiếc xe nổ tung!",
    "bastard_urban_2_1": "Đừng lo cho chủ của những chiếc xe đó. Họ chính là lũ zombie ngươi sắp đối mặt trong thử thách tiếp theo!",
    "bastard_zombie_clown_a": "Giờ là tiết mục giải trí cổ điển: ta sẽ thả zombie hề! Gì cơ? Ta nghiêm túc đấy! Chúng có tóc giả, mặt hóa trang, giày mềm oặt và một cặp dao rỉ sét chưa mài. Nếu bắt được ngươi, chúng vẫn băm ngươi thành từng mảnh như lũ zombie khác. Nhưng chúng thích trêu chọc khán giả và chạy vòng rộng quanh ngươi. Nào, hãy thưởng thức tiết mục của những chú hề đi!",
    "bastard_zombie_clown_b": "Hãy thả thêm vài con zombie cùng chú hề tiếp theo!",
    "bastard_zombie_clown_c": "Lũ hề đâu hết rồi?",
    "bastard_urban_3_1": "Tội nghiệp lũ hề! Sao ai cũng ghét hề thế nhỉ?",
    "bastard_urban_4_1": "Đến lúc cho ngươi đối mặt tất cả những gì đã gặp: zombie cưa máy, zombie hề và Farty. Tất cả cùng lúc! Hãy khôn ngoan chọn mục tiêu bắn trước. Ủa, sao ta lại giúp ngươi nhỉ? Thôi, chúng tới rồi!",
    "bastard_urban_4_2": "Xem ngươi tuyệt vọng chiến đấu để giành giật mạng sống thật vui! Sau này sẽ còn nhiều màn trộn đủ loại zombie nữa đấy.",
    "bastard_zombie_runner_a": "Nhắc đến zombie chạy nhanh, ta thích dùng những loài mang dáng dấp động vật. Chúng tên là Snufflehog, quà từ người bạn thân Papa Sangre của ta. Thử giết vài con xem, nếu ngươi có thể!",
    "bastard_urban_5_2": "Tội nghiệp đám Snufflehog! À mà khoan, ta vẫn còn cả một đội quân nhốt dưới phòng thí nghiệm! Ha ha ha! Còn ngươi, chiến binh mù, hãy mua một khẩu súng trường săn cho các thử thách sắp tới. Đến Kho vũ khí mua đi. Nếu thiếu xu, hãy chơi vài ván Vô tận hoặc săn những ngôi sao ngươi bỏ lỡ ở thử thách trước!",
    "bastard_urban_6_1": "Ừm, súng trường săn! Đôi khi nó có thể hạ zombie chỉ bằng một phát. Nâng cấp càng cao càng dễ làm được điều đó. Ngươi sẽ tưởng đây là phép thuật. Nào, thử ngay đi!",
    "bastard_urban_6_2": "Ôi chà! Ngươi đúng là có năng khiếu dùng súng! Hơi đáng sợ đấy. Thôi, sang thử thách tiếp theo nào!",
    "bastard_passerby_jukebox_a": "Ta đã đặt một chiếc máy hát vào đấu trường cùng ngươi. Thỉnh thoảng nó sẽ phát những bản nhạc ta thích nhất. Nếu muốn làm ta tổn thương, cứ bắn cho nó tắt đi!",
    "bastard_urban_7_2": "Nhìn mặt ngươi là ta biết chẳng thích nhạc của ta. Mà ta cũng chẳng thích ngươi! Nhưng đây là máy hát của ta, ta muốn phát nhạc gì thì phát. Giờ đi tiếp đi!",
    "bastard_zombie_horde_b": "Ngay khi ngươi tưởng đã kiểm soát được mọi thứ, ta chỉ cần bấm một nút và bùm! Một bầy zombie đang lao tới!",
    "bastard_urban_8_1": "Ôi, ngươi bày ra đống lộn xộn gì thế này! Xác thối chất đầy đấu trường, ghê quá! Đừng lo, đội dọn dẹp đang đến. Trong lúc đó, cứ tiếp tục giết thêm zombie đi!",
    "bastard_urban_8_2": "Ừm, ta còn ngửi thấy mùi adrenaline từ tận trên này. Giờ ngươi được thư giãn rồi, thử thách kết thúc! À không, chưa đâu! Lại một đợt zombie nữa! Ha ha ha! Đùa thôi, đùa thôi! Ha ha! Hôm nay đến đây là đủ. Ngươi thắng màn này, chiến binh mù!",
    "bastard_urban_9_1": "Biết chương trình này còn thiếu gì không? Một màn hài hước! Ta đã lấy sạch đạn của ngươi, nên thử thách này ngươi chỉ còn chiếc chảo rán để sống sót. Ta thấy chuyện ấy buồn cười muốn chết!",
    "bastard_urban_9_2": "Ha ha ha! Thấy chưa, vui thật mà! Trông ngươi chẳng khác nào đầu bếp đang căng thẳng ở một quán ăn rẻ tiền! Ha ha ha!",
})


def draft_for(sound_key: str | None) -> str | None:
    return ASR_DRAFT_VI.get(sound_key or "")
