"""Inventory every *possible spoken* recording in AudioDefence.

Use the existing sound manifest, not a guessed list:
    python tools/voice_inventory.py
    python tools/voice_inventory.py --write analysis/voice_inventory.json
    python tools/voice_inventory.py --strict

"Possible spoken" is deliberately conservative: encyclopedia previews may
be zombie sound effects rather than spoken language. Listen before tagging
them as translatable. Not every .m4a is a person talking.

The coverage checker fails until every real spoken recording has reviewed
Vietnamese text and a tested playback hook; autogenerated ASR is NOT coverage.
"""
from __future__ import annotations

import argparse
import csv
import importlib.util
import json
from pathlib import Path
from collections import Counter

ROOT = Path(__file__).resolve().parent.parent
SOUNDS = ROOT / "analysis/data/sounds.tsv"
CAPTIONS = ROOT / "audiodefence/game/recorded_voice_text.py"
SHORT_LABELS = ROOT / "audiodefence/game/voice_labels.py"
TUTORIAL_NO_TEXT = {"announcer_tutorial_aimhelp", "announcer_tutorial_aimprompt"}


def _load_module(filename: Path, name: str):
    # Tables are safe to inspect without starting the game or Android.
    spec = importlib.util.spec_from_file_location(name, filename)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def companion_keys():
    return set(_load_module(CAPTIONS, "ad_recorded_voice_text").CHALLENGE_VOICE_LINES)


def short_label_keys():
    return set(_load_module(SHORT_LABELS, "ad_voice_labels").LABELS)


def classify(path: str):
    """Return (group, confirmed_voice), or None for audio without expected speech."""
    pieces = path.split("/")
    if len(pieces) < 3:
        return None
    group = pieces[1]
    key = pieces[-1].rsplit(".", 1)[0]
    if group == "challenges":
        if key.startswith("bastard_"):
            return "challenge_dialogue", True
        if key.startswith("announcer_tutorial_"):
            return "tutorial_voice", True
    elif group in {"gameover_1", "gameover_2", "gameover_3"} and key.startswith("bastard_"):
        return "gameover_dialogue", True
    elif group == "announcer":
        return "announcer", True
    elif group == "_weapons" and key.endswith("_voice"):
        return "weapon_names", True
    elif group == "powerup" and key.endswith("_announce"):
        return "powerup_names", True
    elif group == "revive":
        return "revive_dialogue", True
    elif group == "opener" and ("DRBASTARD" in key or "_VOICE_" in key):
        return "opener_dialogue", True
    elif group == "encyclopedia":
        return "encyclopedia_preview", False
    return None


def inventory():
    reviewed_companions = companion_keys()
    short_labels = short_label_keys()
    items = []
    with SOUNDS.open(encoding="utf-8", newline="") as f:
        for row in csv.DictReader(f, delimiter="\t"):
            path = row["path"]
            result = classify(path)
            if result is None:
                continue
            group, confirmed_voice = result
            key = Path(path).stem
            if group == "tutorial_voice" and key not in TUTORIAL_NO_TEXT:
                state = "tutorial_text_existing"
            elif key in reviewed_companions:
                state = "contextual_companion_existing"
            elif key in short_labels:
                state = "short_label_existing"
            elif not confirmed_voice:
                state = "review_if_voice"
            else:
                state = "needs_transcript_and_tts"
            items.append({
                "path": "game/" + path,
                "key": key,
                "seconds": float(row["duration_s"]),
                "group": group,
                "status": state,
                "verified_transcript": False,
            })
    return sorted(items, key=lambda v: (v["group"], v["path"]))


def main():
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--write", type=Path, help="also write a JSON inventory for review")
    p.add_argument("--strict", action="store_true", help="fail while any candidate lacks a verified transcript")
    args = p.parse_args()
    entries = inventory()
    groups = Counter(v["group"] for v in entries)
    states = Counter(v["status"] for v in entries)
    print("Potential recorded speech assets:", len(entries))
    for name, n in sorted(groups.items()):
        print(f"  {name}: {n}")
    print("Caption / review status:")
    for name, n in sorted(states.items()):
        print(f"  {name}: {n}")
    print("Total recording time: %.1f minutes" % (sum(v["seconds"] for v in entries) / 60))
    if args.write:
        args.write.parent.mkdir(parents=True, exist_ok=True)
        args.write.write_text(json.dumps(entries, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print("Wrote", args.write)
    # Never call unverified guesses 100% coverage: only a reviewed transcript and
    # tested playback hook counts. Existing tutorial/companion text is separate.
    return 1 if args.strict and any(not x["verified_transcript"] for x in entries) else 0


if __name__ == "__main__":
    raise SystemExit(main())
